name: quiz_learning_app
description: "A Quiz Learning App with responsive UI for Web and Mobile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.0

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4

  # Networking
  dio: ^5.5.0

  # Local Storage
  shared_preferences: ^2.3.2

  # Utilities
  html_unescape: ^2.0.0
  helper_extensions:
    git:
      url: https://github.com/SaadAkram200/helper_extensions.git
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/data/
